//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstDiplome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Repair = new HashSet<Repair>();
            this.Technic = new HashSet<Technic>();
        }
    
        public string FullName { get; set; }
        public string TelephoneEmployee { get; set; }
        public int CodeEmployee { get; set; }
        public string PostEmployee { get; set; }
        public string AdressEmployee { get; set; }
        public Nullable<System.DateTime> DateBirthdayEmployee { get; set; }
        public string Passport { get; set; }
        public string Issued { get; set; }
        public string EmailEmployees { get; set; }
        public Nullable<int> GenderEmployess { get; set; }
    
        public virtual TypesGender TypesGender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Technic> Technic { get; set; }
    }
}
