//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstDiplome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technic()
        {
            this.Repair = new HashSet<Repair>();
        }
    
        public int CodeEquipment { get; set; }
        public string NameEquipment { get; set; }
        public Nullable<int> Suppliers { get; set; }
        public string Description { get; set; }
        public string Equipment { get; set; }
        public string Image { get; set; }
        public Nullable<int> Availability { get; set; }
        public Nullable<int> Repairs { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<int> Employeers { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
        public Nullable<int> Location { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repair> Repair { get; set; }
        public virtual Repair Repair1 { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TypesAvailability TypesAvailability { get; set; }
        public virtual TypesConditions TypesConditions { get; set; }
        public virtual TypesLocate TypesLocate { get; set; }
    }
}
