//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstDiplome
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int CodeUsers { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public string UserRole { get; set; }
        public Nullable<int> UserGender { get; set; }
        public string UserEmail { get; set; }
        public string UserNumber { get; set; }
        public Nullable<System.DateTime> UserDateOfBirthday { get; set; }
        public string UserFullName { get; set; }
    
        public virtual TypesGender TypesGender { get; set; }
    }
}
